### PR TITLE
Update dynamodb to 2.15.33

### PR DESCRIPTION
**Pull request by moia-pipeline**
Updates [software.amazon.awssdk:dynamodb](https://aws.amazon.com/sdkforjava) from 2.15.29 to 2.15.33.

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/04b9d423d4830f1fd86d680ecef2d6372c8ec937/docs/repo-specific-configuration.md) file.

Have a fantastic day writing Scala!

<details>
<summary>Ignore future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "software.amazon.awssdk", artifactId = "dynamodb" } ]
```
</details>

labels: library-update, semver-patch

### CODE REVIEW

**Comment by joroKr21** [comment]
@saeltz looks like we need to disable the settings that mandates up-to-date branches for merging

**Comment by saeltz** [comment]
@joroKr21, can't Scala Steward be configured to update the branch automatically as dependabot would do?

**Comment by joroKr21** [comment]
Not if we run it once a week 😄

**Comment by saeltz** [comment]
What about using something like this https://github.com/marketplace/actions/auto-update?

**Comment by joroKr21** [comment]
That could work - but I suspect it would mean for N update PRs running the build N + (N - 1) + ... + 1 = N * (N + 1) / 2 times.
And the alternative is not so bad - I think it's perfectly fine to disable the up-to-date requirement for a library.
If there is a semantic merge conflict we will find out during the publish step that runs on merge.

**Comment by saeltz** [comment]
@JannikArndt, you're an Admin. Could you please allow merging non-up-to-date branches?

**Comment by JannikArndt** [comment]
Done ✅ (although you @saeltz have admin rights as well. You should be able to change it here: https://github.com/moia-dev/scynamo/settings/branch_protection_rules/15022101)

**Pull request merged**
