### PR TITLE
Add Monad instances for ScynamoDecoder and ObjectScynamoDecoder

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Review by markus1189 — APPROVED** [review]

**Comment by joroKr21** [comment]
@markus1189 do we release by pushing tags?

**Comment by markus1189** [comment]
My last status is documented here: https://github.com/moia-dev/scynamo/tree/master/maintenance Don't know if anything changed, though ;)

**Comment by joroKr21** [comment]
But we don't use CircleCI anymore and I don't see a publish step 🤔 Confused now.

**Comment by markus1189** [comment]
Then the answer is probably @JannikArndt :smirk:

**Comment by JannikArndt** [comment]
We had to change it when we open-source the repo, because it now pushes to sonatype and you need to GPG-sign it. Create a tag and run `sbt +publishSigned` locally. According to https://issues.sonatype.org/browse/OSSRH-52948, you should already be able to push to `io.moia`. Then… same as for https://github.com/moia-dev/scala-http-client#publishing 😉

**Pull request merged**
